on:
  release:
    types:
      - created
  workflow_dispatch:
    inputs: null
    
name: Deploy to Dockerhub on release

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Push to DockerHub
      uses: docker/build-push-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: databio/seqcolapi
        tags: latest
        tag_with_ref: true
